[tool.poetry]
name = "ds-final"
version = "0.1.0"
description = ""
authors = ["willy1236 <66502303+willy1236@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
